### ISSUE TITLE
Schedule priority occasionally throws an error

### ISSUE THREAD

**Issue by hsusanoo** [ssricardo/anki-plugins#108]
I just installed the plugin and this error has been thrown 2 times since.

### Error
```
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the [add-on support site](https://help.ankiweb.net/discussions/add-ons/).
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-02-02 19:41:30

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C1CE839C10>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 115, in __del__
  File "asyncio\proactor_events.py", line 79, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
```

**Comment by ssricardo** [comment]
Thanks for reporting. 
With this kind of error, it might be hard to find out, but I'll try checking it

**Comment by ssricardo** [comment]
I couldn't reproduce this specifically, but in the new version I tried to prevent errors better.
Check out the version released today.
