### ISSUE TITLE
fill-the-blanks: Error message in cards where "(?<!)" is cloze deleted

### ISSUE THREAD

**Issue by ulissesAlmeidaJr** [ssricardo/anki-plugins#129]
It happens after I hit the show answer button.

### Example of card:
{{c1::(?<!)}}

### Error Message:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-14 09:45:55
Add-ons possibly involved: ⁨Fill the blanks - Multiple typecloze support, Image Occlusion Enhanced for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/home/junior/.local/share/Anki2/addons21/1933645497/handler.py", line 283, in _onFillBlankAnswer
    reviewer._showAnswer()
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/junior/.local/share/Anki2/addons21/1374772155/main.py", line 278, in on_show_answer
    return _old(self)
  File "aqt.reviewer", line 402, in _showAnswer
  File "aqt.reviewer", line 332, in _mungeQA
  File "aqt.reviewer", line 548, in typeAnsFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/junior/.local/share/Anki2/addons21/1933645497/handler.py", line 96, in <lambda>
    lambda _, buf, _old: self.typeAnsAnswerFilter(buf, _old), "around")
  File "/home/junior/.local/share/Anki2/addons21/1933645497/handler.py", line 235, in typeAnsAnswerFilter
    result = re.sub(r'<span class="?cloze\s*"?(\s*data-ordinal="\d\d?")?>%s</span>' % html.escape(field.value),
  File "re", line 210, in sub
  File "re", line 304, in _compile
  File "sre_compile", line 764, in compile
  File "sre_parse", line 948, in parse
  File "sre_parse", line 443, in _parse_sub
  File "sre_parse", line 823, in _parse
re.error: unknown extension ?& at position 52

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "aqt.reviewer", line 730, in _onTypedAnswer
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/junior/.local/share/Anki2/addons21/1374772155/main.py", line 278, in on_show_answer
    return _old(self)
  File "aqt.reviewer", line 402, in _showAnswer
  File "aqt.reviewer", line 332, in _mungeQA
  File "aqt.reviewer", line 548, in typeAnsFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/junior/.local/share/Anki2/addons21/1933645497/handler.py", line 96, in <lambda>
    lambda _, buf, _old: self.typeAnsAnswerFilter(buf, _old), "around")
  File "/home/junior/.local/share/Anki2/addons21/1933645497/handler.py", line 235, in typeAnsAnswerFilter
    result = re.sub(r'<span class="?cloze\s*"?(\s*data-ordinal="\d\d?")?>%s</span>' % html.escape(field.value),
  File "re", line 210, in sub
  File "re", line 304, in _compile
  File "sre_compile", line 764, in compile
  File "sre_parse", line 948, in parse
  File "sre_parse", line 443, in _parse_sub
  File "sre_parse", line 823, in _parse
re.error: unknown extension ?& at position 52

**Comment by lightmotive** [comment]
Hey @ulissesAlmeidaJr, I wasn't able to reproduce that issue with the following card HTML:

```html
Test {{c1::(?&lt;!)}} end
```

After hitting Show Answer with correct text:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/7719153/213314505-ef077c7a-54a7-4277-833e-44057cd52742.png">

After hitting Show Answer with incorrect text:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/7719153/213314625-519d8f49-8487-4053-b7da-f55b49794aea.png">

Differences in my environment:

- Using Anki 2.1.56 (you're using 2.1.54)
- Not using the [Image Occlusion Enhanced](https://ankiweb.net/shared/info/1374772155) add-on

Would you please try the following and report back what happens for each?

- Disable the Image Occlusion Enhanced add-on and try again. Does that resolve the issue?
- If possible, update your Anki version to 2.1.56 (backup first; it might break other add-ons you're using if they don't yet support the latest release). Does that resolve the issue either with or without the Image Occlusion Enhanced add-on?

**Comment by ssricardo** [comment]
This is is old.
I just run a test, with the described content. 
And it’s working fine.

That’s using current version of Anki and the new-integration for this addon (the old integration will be removed soon)
