### ISSUE TITLE
Failed to load on Ubuntu 18.04

### ISSUE THREAD

**Issue by tdillenburg** [ssricardo/anki-plugins#17]
Hi, the following error message showed up when trying to load the addon on Ubuntu 18.04 on Anki 2.1.

```
Traceback (most recent call last):
File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons __import__(dir)
File "/home/tiago/.local/share/Anki2/addons21/1259478414/__init__.py", line 9, in <module> run()
File "/home/tiago/.local/share/Anki2/addons21/1259478414/controller.py", line 65, in run controllerInstance.setupBindings()
File "/home/tiago/.local/share/Anki2/addons21/1259478414/controller.py", line 120, in setupBindings
EditorWebView._onPaste = self._wrapOnPaste(EditorWebView._onPaste) AttributeError: type object 'EditorWebView' has no attribute '_onPaste'
```

**Comment by ssricardo** [comment]
Hey!
That's odd. I checked multiple releases of Anki (2.1.x) and that definition does exist in all of them.

I'll have my Linux machine just in about 10 days. Then, I'll test it on Linux.
Meanwhile, I updated it to just avoid throwing that error. The *paste handling* will be disabled in such  case.

**Comment by ssricardo** [comment]
Hey @TiagoDillenburg .

I tested it on Ubuntu (actually Linux Mint), and it worked without any error.
Do you still have that problem in yours?

**Comment by ssricardo** [comment]
Tested recently on Ubuntu, and working.
So I'm closing this ticket
