### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by drmarmalademd** [ssricardo/anki-plugins#62]
See below. The only thing that has changed was I added AnKing's customize background add-on today, but everything was working fine for a while before it started throwing this error.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-03-25 15:59:30
Add-ons possibly involved: ⁨Opening the same window multiple time, Web Browser - Search terms Import texts and images automatically⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/<>/Library/Application Support/Anki2/addons21/864545277/browser.py", line 98, in clozeBrowser
    fn(evt)
  File "aqt/main.py", line 942, in closeEvent
  File "aqt/main.py", line 408, in unloadProfileAndExit
  File "aqt/main.py", line 383, in unloadProfile
  File "aqt/main.py", line 476, in unloadCollection
  File "aqt/main.py", line 747, in closeAllWindows
  File "/Users/<>/Library/Application Support/Anki2/addons21/354407385/__init__.py", line 112, in closeAll
    onsuccess()
  File "aqt/main.py", line 474, in callback
  File "aqt/main.py", line 376, in callback
  File "aqt/main.py", line 396, in _unloadProfile
  File "aqt/main.py", line 854, in maybeAutoSync
  File "aqt/main.py", line 870, in _sync
  File "aqt/sync.py", line 32, in sync
  File "aqt/sync.py", line 55, in _sync
AttributeError: 'NoneType' object has no attribute 'wantCancel'

**Comment by ssricardo** [comment]
Hi. Could you test it with the other addon disabled?
And do you have the link for the source of AnKing addon?

**Comment by drmarmalademd** [comment]
Sure thing. This is the AnKing link: https://ankiweb.net/shared/info/1210908941
And I just tried it, and it works. So it may be the other add-on. I'll contact that creator!
