### ISSUE TITLE
Markdown Support - With Batch n Preview causes error when used with Browser External Note Editor

### ISSUE THREAD

**Issue by SEE-ICT** [ssricardo/anki-plugins#77]
Problem description

Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?

I open the browser and choose a card. I then click File|Edit in new window. I go to the new window and click on a field. I click Close for the new window. All fine so far. I then click on a field in the original browser window. Anki then sometimes, but not always, either immediately after I close the window or after the close when I click on a field in the original browser, throws an error.

Checklist

Please replace the space inside the brackets with an x if the following items apply:

    [X ] I've restarted Anki to see if it helps
    [X ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
    [X ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download

    I've tried to disable other add-ons to see if there are any interactions present

There is a clear interaction with add-on 1996266159 (External Note Editor for the Browser), since the problem does not occur if 1996266159 is not used.

    [ ] My issue disappears when I hold shift while starting Anki.

Well, yes, the problem does disappear. But then so does Browser External Note Editor and Markdown Support - With Batch n Preview.

    [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

Information about your Anki set-up

Please fill out the section corresponding with your Anki version:
If you are using Anki 2.1

Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.31 (13476503) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-29 21:32:01

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\editor.py", line 457, in oncallback
  File "aqt\gui_hooks.py", line 1456, in __call__
  File "anki\hooks.py", line 583, in runHook
  File "D:\Program Data\Anki\addons21\1259478414\controller.py", line 236, in onLoadNote
    self._updatePreview()
  File "D:\Program Data\Anki\addons21\1259478414\controller.py", line 320, in _updatePreview
    self._editorReference.web.eval('cleanPreview();')
  File "aqt\webview.py", line 481, in eval
  File "aqt\webview.py", line 484, in evalWithCallback
  File "aqt\webview.py", line 501, in _queueAction
  File "aqt\webview.py", line 508, in _maybeRunActions
  File "aqt\webview.py", line 497, in _evalWithCallback
RuntimeError: wrapped C/C++ object of type EditorWebView has been deleted

If you are using Anki 2.0

ONLY IF YOU ARE USING ANKI 2.0: Please open Anki, go to Help → About, find the two lines starting with Version: and Qt, and copy-paste them between the backticks below:

Please fill in details about your operating system (Windows/macOS/Linux, which version):

    OS: W10 Pro
    version: Build 19041.450

Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:
Error message (if any)

If you've received an error message, please copy and paste it between the backticks below:

**Comment by ssricardo** [comment]
Thank you for the description. I'll install _External Note Editor for the Browser_ and try to reproduce when I get the chance...

**Comment by ssricardo** [comment]
The Markdown addon hasn’t been maintained currently.
Therefore, closing the issue.
 
I think there are other addons for markdown, working better. Check them out
